
CREATE TABLE batches(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,slug text NOT NULL UNIQUE,entry_year int NOT NULL CHECK(entry_year BETWEEN 1900 AND 2200),graduation_year int,description text NOT NULL DEFAULT '',status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','GRADUATED','ARCHIVED')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK(graduation_year IS NULL OR graduation_year>=entry_year));
CREATE TABLE batch_memberships(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),batch_id uuid NOT NULL REFERENCES batches(id),user_id uuid NOT NULL REFERENCES users(id),status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','SUSPENDED','LEFT','GRADUATED')),joined_at timestamptz NOT NULL DEFAULT now(),ended_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(batch_id,user_id),UNIQUE(batch_id,id));
CREATE INDEX memberships_user ON batch_memberships(user_id,status,batch_id);
CREATE TABLE roles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),code text NOT NULL UNIQUE,name text NOT NULL,scope text NOT NULL CHECK(scope IN ('BATCH','PLATFORM')),is_system_role boolean NOT NULL DEFAULT true,UNIQUE(id,scope));
CREATE TABLE permissions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),code text NOT NULL UNIQUE,scope text NOT NULL CHECK(scope IN ('BATCH','PLATFORM')),UNIQUE(id,scope));
CREATE TABLE role_permissions(role_id uuid NOT NULL,permission_id uuid NOT NULL,scope text NOT NULL,PRIMARY KEY(role_id,permission_id),FOREIGN KEY(role_id,scope) REFERENCES roles(id,scope),FOREIGN KEY(permission_id,scope) REFERENCES permissions(id,scope));
CREATE TABLE membership_roles(membership_id uuid NOT NULL REFERENCES batch_memberships(id),role_id uuid NOT NULL,scope text NOT NULL DEFAULT 'BATCH' CHECK(scope='BATCH'),assigned_by uuid REFERENCES users(id),assigned_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(membership_id,role_id),FOREIGN KEY(role_id,scope) REFERENCES roles(id,scope));
CREATE TABLE user_platform_roles(user_id uuid NOT NULL REFERENCES users(id),role_id uuid NOT NULL,scope text NOT NULL DEFAULT 'PLATFORM' CHECK(scope='PLATFORM'),assigned_by uuid REFERENCES users(id),assigned_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(user_id,role_id),FOREIGN KEY(role_id,scope) REFERENCES roles(id,scope));
CREATE TABLE audit_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),batch_id uuid REFERENCES batches(id),actor_user_id uuid REFERENCES users(id),action text NOT NULL,entity_type text NOT NULL,entity_id uuid NOT NULL,new_values jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX audit_batch ON audit_logs(batch_id,created_at DESC,id DESC);
CREATE FUNCTION protect_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'audit records are append-only'; END $$;
CREATE TRIGGER audit_immutable BEFORE UPDATE OR DELETE ON audit_logs FOR EACH ROW EXECUTE FUNCTION protect_audit();
CREATE FUNCTION require_student() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE mid uuid;
BEGIN
 IF TG_TABLE_NAME='batch_memberships' THEN mid:=NEW.id; ELSE mid:=OLD.membership_id; END IF;
 IF EXISTS(SELECT 1 FROM batch_memberships WHERE id=mid AND status='ACTIVE') AND NOT EXISTS(SELECT 1 FROM membership_roles mr JOIN roles r ON r.id=mr.role_id WHERE mr.membership_id=mid AND r.code='STUDENT') THEN RAISE EXCEPTION 'active membership requires STUDENT' USING ERRCODE='23514'; END IF;
 RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER membership_student AFTER INSERT OR UPDATE ON batch_memberships DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION require_student();
CREATE CONSTRAINT TRIGGER preserve_student AFTER DELETE OR UPDATE ON membership_roles DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION require_student();
INSERT INTO permissions(code,scope) VALUES('announcement.create','BATCH');
INSERT INTO permissions(code,scope) VALUES('announcement.delete','BATCH');
INSERT INTO permissions(code,scope) VALUES('announcement.publish','BATCH');
INSERT INTO permissions(code,scope) VALUES('announcement.update','BATCH');
INSERT INTO permissions(code,scope) VALUES('announcement.view','BATCH');
INSERT INTO permissions(code,scope) VALUES('audit.view','BATCH');
INSERT INTO permissions(code,scope) VALUES('batch.archive','PLATFORM');
INSERT INTO permissions(code,scope) VALUES('batch.create','PLATFORM');
INSERT INTO permissions(code,scope) VALUES('batch.manage','BATCH');
INSERT INTO permissions(code,scope) VALUES('batch.profile.manage','BATCH');
INSERT INTO permissions(code,scope) VALUES('batch.view','BATCH');
INSERT INTO permissions(code,scope) VALUES('complaint.create','BATCH');
INSERT INTO permissions(code,scope) VALUES('complaint.resolve','BATCH');
INSERT INTO permissions(code,scope) VALUES('complaint.respond','BATCH');
INSERT INTO permissions(code,scope) VALUES('complaint.view_all','BATCH');
INSERT INTO permissions(code,scope) VALUES('complaint.view_own','BATCH');
INSERT INTO permissions(code,scope) VALUES('event.manage','BATCH');
INSERT INTO permissions(code,scope) VALUES('event.view','BATCH');
INSERT INTO permissions(code,scope) VALUES('feedback.create','BATCH');
INSERT INTO permissions(code,scope) VALUES('feedback.manage','BATCH');
INSERT INTO permissions(code,scope) VALUES('feedback.view','BATCH');
INSERT INTO permissions(code,scope) VALUES('gallery.manage','PLATFORM');
INSERT INTO permissions(code,scope) VALUES('lesson.manage','BATCH');
INSERT INTO permissions(code,scope) VALUES('lesson.view','BATCH');
INSERT INTO permissions(code,scope) VALUES('link.manage','BATCH');
INSERT INTO permissions(code,scope) VALUES('link.view','BATCH');
INSERT INTO permissions(code,scope) VALUES('membership.manage','BATCH');
INSERT INTO permissions(code,scope) VALUES('membership.view','BATCH');
INSERT INTO permissions(code,scope) VALUES('module.manage','BATCH');
INSERT INTO permissions(code,scope) VALUES('module.view','BATCH');
INSERT INTO permissions(code,scope) VALUES('platform_audit.view','PLATFORM');
INSERT INTO permissions(code,scope) VALUES('platform_user.manage','PLATFORM');
INSERT INTO permissions(code,scope) VALUES('position.manage','BATCH');
INSERT INTO permissions(code,scope) VALUES('position.view','BATCH');
INSERT INTO permissions(code,scope) VALUES('resource.create','BATCH');
INSERT INTO permissions(code,scope) VALUES('resource.delete','BATCH');
INSERT INTO permissions(code,scope) VALUES('resource.publish','BATCH');
INSERT INTO permissions(code,scope) VALUES('resource.update','BATCH');
INSERT INTO permissions(code,scope) VALUES('resource.view','BATCH');
INSERT INTO permissions(code,scope) VALUES('role.assign','BATCH');
INSERT INTO permissions(code,scope) VALUES('semester.manage','BATCH');
INSERT INTO permissions(code,scope) VALUES('semester.view','BATCH');
INSERT INTO roles(code,name,scope) VALUES('STUDENT','STUDENT','BATCH');
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='STUDENT' AND p.code='batch.view';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='STUDENT' AND p.code='membership.view';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='STUDENT' AND p.code='semester.view';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='STUDENT' AND p.code='module.view';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='STUDENT' AND p.code='announcement.view';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='STUDENT' AND p.code='resource.view';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='STUDENT' AND p.code='lesson.view';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='STUDENT' AND p.code='link.view';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='STUDENT' AND p.code='event.view';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='STUDENT' AND p.code='position.view';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='STUDENT' AND p.code='complaint.create';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='STUDENT' AND p.code='complaint.view_own';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='STUDENT' AND p.code='feedback.create';
INSERT INTO roles(code,name,scope) VALUES('BATCH_REP','BATCH_REP','BATCH');
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='batch.manage';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='membership.manage';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='role.assign';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='feedback.view';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='feedback.manage';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='audit.view';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='semester.manage';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='module.manage';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='announcement.create';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='announcement.update';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='announcement.delete';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='announcement.publish';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='resource.create';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='resource.update';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='resource.delete';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='resource.publish';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='lesson.manage';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='link.manage';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='event.manage';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='position.manage';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='BATCH_REP' AND p.code='batch.profile.manage';
INSERT INTO roles(code,name,scope) VALUES('CONTENT_MANAGER','CONTENT_MANAGER','BATCH');
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='CONTENT_MANAGER' AND p.code='announcement.create';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='CONTENT_MANAGER' AND p.code='announcement.update';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='CONTENT_MANAGER' AND p.code='announcement.delete';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='CONTENT_MANAGER' AND p.code='announcement.publish';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='CONTENT_MANAGER' AND p.code='resource.create';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='CONTENT_MANAGER' AND p.code='resource.update';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='CONTENT_MANAGER' AND p.code='resource.delete';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='CONTENT_MANAGER' AND p.code='resource.publish';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='CONTENT_MANAGER' AND p.code='lesson.manage';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='CONTENT_MANAGER' AND p.code='link.manage';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='CONTENT_MANAGER' AND p.code='event.manage';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='CONTENT_MANAGER' AND p.code='position.manage';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='CONTENT_MANAGER' AND p.code='batch.profile.manage';
INSERT INTO roles(code,name,scope) VALUES('ACADEMIC_REP','ACADEMIC_REP','BATCH');
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='ACADEMIC_REP' AND p.code='semester.manage';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='ACADEMIC_REP' AND p.code='module.manage';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='ACADEMIC_REP' AND p.code='announcement.create';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='ACADEMIC_REP' AND p.code='announcement.update';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='ACADEMIC_REP' AND p.code='announcement.delete';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='ACADEMIC_REP' AND p.code='announcement.publish';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='ACADEMIC_REP' AND p.code='resource.create';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='ACADEMIC_REP' AND p.code='resource.update';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='ACADEMIC_REP' AND p.code='resource.delete';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='ACADEMIC_REP' AND p.code='resource.publish';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='ACADEMIC_REP' AND p.code='lesson.manage';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='ACADEMIC_REP' AND p.code='link.manage';
INSERT INTO roles(code,name,scope) VALUES('COMPLAINT_MANAGER','COMPLAINT_MANAGER','BATCH');
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='COMPLAINT_MANAGER' AND p.code='complaint.view_all';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='COMPLAINT_MANAGER' AND p.code='complaint.respond';
INSERT INTO role_permissions SELECT r.id,p.id,'BATCH' FROM roles r,permissions p WHERE r.code='COMPLAINT_MANAGER' AND p.code='complaint.resolve';
INSERT INTO roles(code,name,scope) VALUES('PLATFORM_ADMIN','PLATFORM_ADMIN','PLATFORM');
INSERT INTO role_permissions SELECT r.id,p.id,'PLATFORM' FROM roles r,permissions p WHERE r.code='PLATFORM_ADMIN' AND p.code='batch.create';
INSERT INTO role_permissions SELECT r.id,p.id,'PLATFORM' FROM roles r,permissions p WHERE r.code='PLATFORM_ADMIN' AND p.code='batch.archive';
INSERT INTO role_permissions SELECT r.id,p.id,'PLATFORM' FROM roles r,permissions p WHERE r.code='PLATFORM_ADMIN' AND p.code='platform_user.manage';
INSERT INTO role_permissions SELECT r.id,p.id,'PLATFORM' FROM roles r,permissions p WHERE r.code='PLATFORM_ADMIN' AND p.code='gallery.manage';
INSERT INTO role_permissions SELECT r.id,p.id,'PLATFORM' FROM roles r,permissions p WHERE r.code='PLATFORM_ADMIN' AND p.code='platform_audit.view';
