DROP TABLE IF EXISTS position_assignments CASCADE;
DROP TABLE IF EXISTS batch_positions CASCADE;
DROP TABLE IF EXISTS batch_profiles CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS useful_links CASCADE;
DROP TABLE IF EXISTS recorded_lessons CASCADE;
