DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS notification_events CASCADE;
DROP TABLE IF EXISTS feedback CASCADE;
DROP TABLE IF EXISTS complaint_messages CASCADE;
DROP TABLE IF EXISTS complaints CASCADE;
